spring.application.name=finaltodo
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/finaltododb
spring.datasource.username=root
spring.datasource.password=KINGsaha1926@#$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect